### ISSUE TITLE
toModel call fails to completely strip extended functions and internal properties

### ISSUE THREAD

**Issue by oising** [coderenaissance/knockout.viewmodel#18]
I noticed that if I extend a viewModel with functions through your `options: { extend: ... }` parameter, they are not removed completely after a toModel call. Their implementations are gone, but the properties still exist on the model, albeit with undefined values. This breaks OData round tripping. Also, some of your custom properties linger, namely "..IdName". Here's what I have to do in my save code to strip off the vestigial stuff:

```
        ViewModel.prototype.saveSheet = function () {
            if(this.selectedSheet()) {
                var model = ko.viewmodel.toModel(this.selectedSheet());
                delete model["..IdName"];
                delete model["save"];
                model.Tasks.results.forEach(function (task) {
                    delete task["..idName"];
                    delete task["getScopeName"];
                    delete task["getPoints"];
                    delete task["cancel"];
                    delete task["hasChanges"];
                });
                model.Points.results.forEach(function (point) {
                    delete point["..idName"];
                });
                console.log(model);
                return this.service.saveSheet(model);
            }
            throw "No selected sheet.";
        };
```

Please comment back if you cannot repro (seems doubtful) and I'll furnish a JSON instance that you can repro with.

**Comment by coderenaissance** [comment]
"..idName" was added directly by the plugin... the others may have been added by knockout? Will look into it, Thanks!

**Comment by oising** [comment]
The others were added by me with the first `fromModel` call, for example:

```
var viewModel = ko.viewmodel.fromModel(model, {
    extend: {
        "{root}.Tasks.results" : function(task) {
            task.getScopeName = function() { ... }.bind(task);
        }
    });
```

So, I know where they are coming from :-) It's just that the `toModel` call does not _undo_ this fully. I would expect `toModel` to return me exactly what I passed to `fromModel`.

**Comment by coderenaissance** [comment]
Once this change is released computed values and a functions added to an object with extend will be removed completely (hasOwnProperty will return false). 

A different scenario would be extending with observables, as they would be added to your model when calling toModel. If you need to work around this then in your extend method consider wrapping your object in an observable and extending the observable. 

```
 var options = {
    extend:{
     "{root}.prop":function(prop){
       prop.someFunction = function(){};
       prop = ko.observable(prop);
       prop.isVisible = ko.observable(false);
       return prop;
     }
   }
 };
```

This works well though you will have to modify some of your bindings to compensate. 

```
data-bind="click:prop().someFunction, visible:prop.isVisible"
```

Note one has () and the other doesn't... also this wouldn't work with the with binding because isVisible wouldn't be available.

I may consider making entend like custom and allow map and unmap to be optionally provided.... then any undesirables could be stripped off after standard unmapping had taken place. Thoughts?

**Comment by coderenaissance** [comment]
I plan to release this and other fixes by this weekend, but if you need it sooner you can grab it from my Next-Version branch.
