### ISSUE TITLE
It's not possible to map a non-Object model

### ISSUE THREAD

**Issue by kristofferlindvall** [coderenaissance/knockout.viewmodel#28]
Lets say I define a new "class", called ViewModel:

var ViewModel = (function () {
    function ViewModel(posts) {
        this.posts = posts;
        this.newCount = 0;
    }
    return ViewModel;
})();

I then instantiate this like so:

var model = new ViewModel(posts);

Now, model will not be mapped by knockout.viewmodel, because knockout.viewmodel expects an object whose .constructor === Object, and in this case, it's .constructor === ViewModel.

**Comment by coderenaissance** [comment]
This is by design. The viewmodel plugin is designed to process json objects returned with an ajax call. A lot of speed is gained by limiting processing strictly to json objects. I believe you can still accomplish what you want like this:

var model = {
    posts:posts,
    newCount: 0
};

var viewmodel = ko.viewmodel.fromModel(model);

**Comment by kristofferlindvall** [comment]
You're right. I didn't think this through enoguh. There's of course not much use in using knockout.viewmodel on anything other than a json/Object. If you're in control of creating the object, you might as well create the view model youeself in the first place.
